### ISSUE TITLE
Add glue for providing details WoRMS information

### ISSUE THREAD

**Issue by eblondel** [gradesystem/grade-glue#7]
To add some glue for enriching the ``asfis`` - ``worms`` pure code mapping with ``worms`` detailed (textual) information. The requirement has been extended to provide the taxonomic code hierarchy covering the ASFIS species list.

Inputs:
* code mapping is provided as ``comet`` mapping xml asset,
* ``worms`` dataset as csv asset.

Outputs: 
* Code hierarchy as ``CsvAsset``,
* subset of worms made of code / text as ``CsvAsset``

**Comment by fabiosimeoni** [comment]
to be precise, and as far as I understand it, we do not need an *enrichment* of the `asfis-worms` mappings.  we need to extract the subset of`worms` of all the species whose code occurs in the `asfis-worms` mapping. in particular, we do not need to add more information to that mapping, rather produce a second, separate datasets.

**Comment by eblondel** [comment]
Thanks @fabiosimeoni indeed on this i had a doubt ;-) At now the output is a csv asset. The only additional column is the ASFIS alphacode, but if you want i can remove it, no problem, so it the logic will be strictly a filter. Let me know

**Comment by fabiosimeoni** [comment]
tell you what, leave it as it is since it's just an extra field. it cannot do much harm and may turn out to be an optimisation. will check with @cbaldassarre.  thanks!

**Comment by eblondel** [comment]
is it everything ok? if yes, please close the ticket.

**Comment by fabiosimeoni** [comment]
am waiting for C.Baldassarre to give the OK, only he can judge the data. will close as soon as I know something.

**Comment by eblondel** [comment]
The new glue has been implemented. I've pushed the 2 assets to Grade. The code hierarchy dataset is named ``worms-subset-hierarchy``, and the derived codelist (handling name, rank & author) is named ``worms-subset-codelist``.
